import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const packageRoot = join(import.meta.dir, '..');
const generatedDrizzleDir = join(packageRoot, 'generated', 'drizzle');
const outputPath = join(packageRoot, 'generated', 'migrations.ts');
const migrations = readdirSync(generatedDrizzleDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()
  .map((name) => {
    const timestamp = Number.parseInt(name.split('_', 1)[0] ?? '', 10);
    if (!Number.isSafeInteger(timestamp)) {
      throw new Error(`Invalid Drizzle migration directory name: ${name}`);
    }
    return { name, timestamp };
  });

const imports = migrations
  .map(
    ({ name }, index) => `import migration${index}Path from './drizzle/${name}/migration.sql' with { type: 'file' };`,
  )
  .join('\n');

const journalEntries = migrations
  .map(
    ({ name, timestamp }, index) => `  {
    name: '${name}',
    timestamp: ${timestamp},
    sql: readFileSync(migration${index}Path, 'utf8'),
  },`,
  )
  .join('\n');

const content = `// Generated by scripts/generateMigrations.ts — do not edit.
import { readFileSync } from 'node:fs';
import type { MigrationsJournal } from 'drizzle-orm/migrator';
${imports}

export const storageMigrationsTable = '_contextbridge_migrations';
export const storageMigrationsJournal = [
${journalEntries}
] satisfies MigrationsJournal;
`;

writeFileSync(outputPath, content);
