#!/usr/bin/env bun
/**
 * Generate MDX pages for the docs site CLI reference by introspecting the
 * Commander program. Output is gitignored — re-run via `bun run gen:docs`
 * (or implicitly via the website's pre-{dev,build,typecheck,test} scripts).
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Command, Option } from 'commander';
import { createProgram } from '#src/commands/index.ts';
import { createStubContext } from '#src/testHelpers/index.ts';

const OUT_DIR = fileURLToPath(new URL('../../../packages/website/src/content/docs/cli/', import.meta.url));

await main();

async function main(): Promise<void> {
  const { context } = createStubContext();
  const program = createProgram(context);
  const programName = program.name();

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const commands = collectCommands(program, []);
  await writeOverview(commands);
  for (const entry of commands) {
    await writeCommandPage(programName, entry);
  }

  console.log(`generated ${commands.length} CLI reference pages → ${OUT_DIR}`);
}

interface CommandEntry {
  command: Command;
  segments: string[];
}

function collectCommands(cmd: Command, parents: string[]): CommandEntry[] {
  const out: CommandEntry[] = [];
  for (const sub of cmd.commands) {
    if (sub.name() === 'help') continue;
    const segments = [...parents, sub.name()];
    out.push({ command: sub, segments });
    if (sub.commands.length > 0) {
      out.push(...collectCommands(sub, segments));
    }
  }
  return out;
}

async function writeOverview(commands: CommandEntry[]): Promise<void> {
  // Top-level only — nested subcommands are reachable via each parent page and
  // Starlight's autogenerated sidebar.
  const rows = commands
    .filter(({ segments }) => segments.length === 1)
    .map(({ command, segments }) => `| [\`${segments[0]}\`](/cli/${segments[0]}/) | ${command.description() || '—'} |`);

  const lines = [
    '---',
    'title: CLI reference',
    'description: Subcommands, flags, and exit codes for the contextbridge binary.',
    'sidebar:',
    '  order: 0',
    '---',
    '',
    '## Subcommands',
    '',
    '| Command | Purpose |',
    '| --- | --- |',
    ...rows,
    '',
  ];

  await writeFile(join(OUT_DIR, 'index.mdx'), lines.join('\n'));
}

async function writeCommandPage(programName: string, { command, segments }: CommandEntry): Promise<void> {
  const slug = segments.join('/');
  const filePath = join(OUT_DIR, `${slug}.mdx`);
  await mkdir(dirname(filePath), { recursive: true });

  const title = segments.join(' ');
  const description = command.description() || `${title} command.`;

  const lines: string[] = [
    '---',
    `title: ${quoteYaml(title)}`,
    `description: ${quoteYaml(description)}`,
    '---',
    '',
    '## Usage',
    '',
    '```sh',
    `${programName} ${title} ${command.usage()}`.trim(),
    '```',
    '',
  ];

  if (command.registeredArguments.length > 0) {
    lines.push('## Arguments', '', '| Name | Description |', '| --- | --- |');
    for (const arg of command.registeredArguments) {
      const name = arg.required ? `\`<${arg.name()}>\`` : `\`[${arg.name()}]\``;
      lines.push(`| ${name} | ${arg.description || '—'} |`);
    }
    lines.push('');
  }

  const userOptions = command.options.filter((opt: Option) => opt.long !== '--help');
  if (userOptions.length > 0) {
    lines.push('## Options', '', '| Flag | Description |', '| --- | --- |');
    for (const opt of userOptions) {
      const def = opt.defaultValue !== undefined ? ` *(default: \`${JSON.stringify(opt.defaultValue)}\`)*` : '';
      const choiceText = opt.argChoices ? ` *(choices: ${opt.argChoices.map((c) => `\`${c}\``).join(', ')})*` : '';
      lines.push(`| \`${opt.flags}\` | ${opt.description}${choiceText}${def} |`);
    }
    lines.push('');
  }

  const subs = command.commands.filter((c) => c.name() !== 'help');
  if (subs.length > 0) {
    lines.push('## Subcommands', '', '| Command | Purpose |', '| --- | --- |');
    for (const sub of subs) {
      const subSegments = [...segments, sub.name()];
      lines.push(`| [\`${subSegments.join(' ')}\`](/cli/${subSegments.join('/')}/) | ${sub.description() || '—'} |`);
    }
    lines.push('');
  }

  await writeFile(filePath, lines.join('\n'));
}

function quoteYaml(value: string): string {
  if (/[:#&*[\]{}|>!%@`,]/.test(value) || /['"\n]/.test(value)) {
    return JSON.stringify(value);
  }
  return value;
}
